### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by rausnitz** [iamjono/SwiftRandom#2]
I made the function below to generate random strings from the characters in a given string. For example, `"ABCDEFGHIJK".randomStringFromString(length: 3)` could return something like `"GBF"`.

```
import SwiftRandom

extension String {    
    public func randomStringFromString(length: Int) -> String {
        let characters: [String] = self.map { String($0) }
        var randomString = ""
        for _ in 0 ..< length {
            let index = Int.random(range: 0 ..< characters.count )
            randomString += characters[index]
        }
        return randomString
    }
}
```

Occasionally I've been getting `Fatal error: Index out of range`. So I changed line 4 of the function to `let index = Int.random(range: 0 ..< characters.count - 1)` and that seems to solve the problem. But I thought `..<` should've kept me from getting out of range. Was there a mistake in my function or is it an issue in SwiftRandom?

**Comment by iamjono** [comment]
Weird. I'll investigate further. Thanks for seeing this
